# Generated by Django 4.2.7 on 2024-01-03 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrdemServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True, null=True)),
                ('dt_criacao', models.DateTimeField(null=True)),
                ('dt_edicao', models.DateTimeField(null=True)),
                ('user_criacao', models.CharField(max_length=255, null=True)),
                ('user_edicao', models.CharField(max_length=255, null=True)),
                ('hr_entrega', models.CharField(max_length=5, null=True)),
            ],
            options={
                'db_table': 'ordemservico',
            },
        ),
        migrations.CreateModel(
            name='OrdemServicoStatus',
            fields=[
                ('status', models.BooleanField(default=True, null=True)),
                ('dt_criacao', models.DateTimeField(null=True)),
                ('dt_edicao', models.DateTimeField(null=True)),
                ('user_criacao', models.CharField(max_length=255, null=True)),
                ('user_edicao', models.CharField(max_length=255, null=True)),
                ('nome', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('ordem', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'ordemservico_status',
            },
        ),
        migrations.CreateModel(
            name='OrdemServicoStatusLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True, null=True)),
                ('dt_criacao', models.DateTimeField(null=True)),
                ('dt_edicao', models.DateTimeField(null=True)),
                ('user_criacao', models.CharField(max_length=255, null=True)),
                ('user_edicao', models.CharField(max_length=255, null=True)),
                ('ordem', models.IntegerField(null=True)),
                ('status_ordem', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ordem_servico.ordemservicostatus')),
            ],
            options={
                'db_table': 'ordemservico_status_log',
            },
        ),
    ]
