# Generated by Django 4.2.7 on 2024-02-04 03:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_alter_usuario_user'),
        ('ordem_servico', '0002_ordemservico_carro_ordemservico_cliente_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordemservico',
            name='responsavel',
        ),
        migrations.AddField(
            model_name='ordemservicostatus',
            name='responsavel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='usuario.usuario'),
        ),
    ]
