# Generated by Django 4.2.7 on 2024-02-02 22:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Filial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True, null=True)),
                ('dt_criacao', models.DateTimeField(null=True)),
                ('dt_edicao', models.DateTimeField(null=True)),
                ('user_criacao', models.CharField(max_length=255, null=True)),
                ('user_edicao', models.CharField(max_length=255, null=True)),
                ('cep', models.CharField(max_length=10, null=True)),
                ('cep_form', models.CharField(max_length=15, null=True)),
                ('municipio', models.CharField(max_length=15, null=True)),
                ('bairro_cep', models.CharField(max_length=100, null=True)),
                ('endereco_cep', models.CharField(max_length=100, null=True)),
                ('endereco_comp_cep', models.CharField(max_length=200, null=True)),
                ('latitude_cep', models.CharField(max_length=200, null=True)),
                ('longitude_cep', models.CharField(max_length=200, null=True)),
                ('tipo_cep', models.CharField(max_length=200, null=True)),
                ('nome', models.CharField(max_length=255, null=True)),
                ('cnpj', models.CharField(max_length=50, null=True)),
                ('cnpj_form', models.CharField(max_length=50, null=True)),
                ('razao_social', models.CharField(max_length=200, null=True)),
                ('nm_fantasia', models.CharField(max_length=200, null=True)),
                ('empresa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='empresa.empresa')),
            ],
            options={
                'db_table': 'empresa_filial',
            },
        ),
    ]
