# Generated by Django 4.2.7 on 2023-12-15 00:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cliente', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True, null=True)),
                ('dt_criacao', models.DateTimeField(null=True)),
                ('dt_edicao', models.DateTimeField(null=True)),
                ('user_criacao', models.CharField(max_length=255, null=True)),
                ('user_edicao', models.CharField(max_length=255, null=True)),
                ('marca', models.CharField(max_length=32, null=True)),
                ('descricao', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'automovel_marca',
            },
        ),
        migrations.CreateModel(
            name='Modelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True, null=True)),
                ('dt_criacao', models.DateTimeField(null=True)),
                ('dt_edicao', models.DateTimeField(null=True)),
                ('user_criacao', models.CharField(max_length=255, null=True)),
                ('user_edicao', models.CharField(max_length=255, null=True)),
                ('modelo', models.CharField(max_length=32, null=True)),
                ('ano_lancamento', models.DateField(null=True)),
                ('potencia_motor', models.IntegerField(null=True)),
                ('chassis', models.IntegerField(null=True)),
                ('combustivel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='combustivel', to='core.tipo')),
                ('marca', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='automovel.marca')),
                ('nm_portas', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='portas', to='core.tipo')),
                ('tipo_motor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='motor', to='core.tipo')),
                ('transmissao', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='transmissao', to='core.tipo')),
            ],
            options={
                'db_table': 'automovel_modelo',
            },
        ),
        migrations.CreateModel(
            name='Automovel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True, null=True)),
                ('dt_criacao', models.DateTimeField(null=True)),
                ('dt_edicao', models.DateTimeField(null=True)),
                ('user_criacao', models.CharField(max_length=255, null=True)),
                ('user_edicao', models.CharField(max_length=255, null=True)),
                ('placa', models.CharField(max_length=7)),
                ('placa_form', models.CharField(max_length=8, null=True)),
                ('quilometragem', models.IntegerField(null=True)),
                ('observacoes', models.CharField(max_length=1024, null=True)),
                ('cor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='cor', to='core.tipo')),
                ('modelo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='automovel.modelo')),
                ('proprietario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cliente.usuario')),
            ],
            options={
                'db_table': 'automovel',
            },
        ),
    ]
