# Generated by Django 4.2.7 on 2023-12-15 02:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client_core', '0005_initial'),
        ('automovel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automovel',
            name='cor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='cor', to='client_core.tipo'),
        ),
        migrations.AlterField(
            model_name='modelo',
            name='combustivel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='combustivel', to='client_core.tipo'),
        ),
        migrations.AlterField(
            model_name='modelo',
            name='nm_portas',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='portas', to='client_core.tipo'),
        ),
        migrations.AlterField(
            model_name='modelo',
            name='tipo_motor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='motor', to='client_core.tipo'),
        ),
        migrations.AlterField(
            model_name='modelo',
            name='transmissao',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='transmissao', to='client_core.tipo'),
        ),
    ]
