# Generated by Django 4.2.7 on 2023-12-15 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automovel', '0002_alter_automovel_cor_alter_modelo_combustivel_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modelo',
            name='chassis',
        ),
        migrations.AddField(
            model_name='automovel',
            name='chassis',
            field=models.IntegerField(null=True),
        ),
    ]
