# Generated by Django 4.2.7 on 2024-02-02 22:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('status', models.BooleanField(default=True, null=True)),
                ('dt_criacao', models.DateTimeField(null=True)),
                ('dt_edicao', models.DateTimeField(null=True)),
                ('user_criacao', models.CharField(max_length=255, null=True)),
                ('user_edicao', models.CharField(max_length=255, null=True)),
                ('nome', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('nm_descritivo', models.CharField(max_length=512, null=True)),
                ('descricao', models.CharField(max_length=1024, null=True)),
                ('modulo', models.CharField(max_length=64, null=True)),
                ('prioridade', models.IntegerField(null=True)),
                ('tela_principal', models.CharField(max_length=255, null=True)),
            ],
            options={
                'db_table': 'sistema_grupo',
            },
        ),
        migrations.CreateModel(
            name='GrupoPontoFuncao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True, null=True)),
                ('dt_criacao', models.DateTimeField(null=True)),
                ('dt_edicao', models.DateTimeField(null=True)),
                ('user_criacao', models.CharField(max_length=255, null=True)),
                ('user_edicao', models.CharField(max_length=255, null=True)),
            ],
            options={
                'db_table': 'sistema_grupo_pontofuncao',
            },
        ),
        migrations.CreateModel(
            name='GrupoUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True, null=True)),
                ('dt_criacao', models.DateTimeField(null=True)),
                ('dt_edicao', models.DateTimeField(null=True)),
                ('user_criacao', models.CharField(max_length=255, null=True)),
                ('user_edicao', models.CharField(max_length=255, null=True)),
            ],
            options={
                'db_table': 'sistema_grupo_user',
            },
        ),
        migrations.CreateModel(
            name='PontoFuncao',
            fields=[
                ('status', models.BooleanField(default=True, null=True)),
                ('dt_criacao', models.DateTimeField(null=True)),
                ('dt_edicao', models.DateTimeField(null=True)),
                ('user_criacao', models.CharField(max_length=255, null=True)),
                ('user_edicao', models.CharField(max_length=255, null=True)),
                ('nome', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('nm_descritivo', models.CharField(max_length=512, null=True)),
                ('descricao', models.CharField(max_length=1024, null=True)),
                ('modulo', models.CharField(max_length=64, null=True)),
                ('prioridade', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'sistema_pontofuncao',
            },
        ),
        migrations.CreateModel(
            name='PontoFuncaoUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True, null=True)),
                ('dt_criacao', models.DateTimeField(null=True)),
                ('dt_edicao', models.DateTimeField(null=True)),
                ('user_criacao', models.CharField(max_length=255, null=True)),
                ('user_edicao', models.CharField(max_length=255, null=True)),
                ('ponto_funcao', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='permissao.pontofuncao')),
            ],
            options={
                'db_table': 'sistema_ponto_funcao_user',
            },
        ),
    ]
