# Generated by Django 4.2.7 on 2023-11-21 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permissao', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupo',
            name='dt_criacao',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='grupo',
            name='dt_edicao',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='grupo',
            name='user_criacao',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='grupo',
            name='user_edicao',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='grupopontofuncao',
            name='dt_criacao',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='grupopontofuncao',
            name='dt_edicao',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='grupopontofuncao',
            name='user_criacao',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='grupopontofuncao',
            name='user_edicao',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pontofuncao',
            name='dt_criacao',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='pontofuncao',
            name='dt_edicao',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='pontofuncao',
            name='user_criacao',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pontofuncao',
            name='user_edicao',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
