# Generated by Django 4.2.7 on 2024-02-02 22:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuario', '0001_initial'),
        ('permissao', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pontofuncaouser',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='usuario.usuario'),
        ),
        migrations.AddField(
            model_name='pontofuncao',
            name='ponto_funcao_pai',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='permissao.pontofuncao'),
        ),
        migrations.AddField(
            model_name='grupouser',
            name='grupo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='permissao.grupo'),
        ),
        migrations.AddField(
            model_name='grupouser',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='usuario.usuario'),
        ),
        migrations.AddField(
            model_name='grupopontofuncao',
            name='grupo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='permissao.grupo'),
        ),
        migrations.AddField(
            model_name='grupopontofuncao',
            name='ponto_funcao',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='permissao.pontofuncao'),
        ),
        migrations.AddField(
            model_name='grupo',
            name='grupo_pai',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='permissao.grupo'),
        ),
    ]
