# Generated by Django 4.2.7 on 2023-11-21 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0003_usuario_dt_criacao_usuario_dt_edicao_usuario_user_and_more'),
        ('permissao', '0002_grupo_dt_criacao_grupo_dt_edicao_grupo_user_criacao_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PontoFuncaoUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True, null=True)),
                ('dt_criacao', models.DateTimeField(null=True)),
                ('dt_edicao', models.DateTimeField(null=True)),
                ('user_criacao', models.CharField(max_length=255, null=True)),
                ('user_edicao', models.CharField(max_length=255, null=True)),
                ('ponto_funcao', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='permissao.pontofuncao')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='usuario.usuario')),
            ],
            options={
                'db_table': 'sistema_ponto_funcao_user',
            },
        ),
        migrations.CreateModel(
            name='GrupoUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True, null=True)),
                ('dt_criacao', models.DateTimeField(null=True)),
                ('dt_edicao', models.DateTimeField(null=True)),
                ('user_criacao', models.CharField(max_length=255, null=True)),
                ('user_edicao', models.CharField(max_length=255, null=True)),
                ('grupo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='permissao.grupo')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='usuario.usuario')),
            ],
            options={
                'db_table': 'sistema_grupo_user',
            },
        ),
    ]
