# Generated by Django 4.2.7 on 2023-12-15 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('automovel', '0002_alter_automovel_cor_alter_modelo_combustivel_and_more'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tipo',
        ),
    ]
