# Generated by Django 4.2.7 on 2023-11-20 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True, null=True)),
                ('nm_completo', models.CharField(max_length=255, null=True)),
                ('idade', models.IntegerField(null=True)),
                ('is_client', models.BooleanField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
