# Generated by Django 4.2.7 on 2023-11-21 11:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_usuariologin'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='dt_criacao',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='dt_edicao',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usuario',
            name='user_criacao',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='user_edicao',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='usuariologin',
            name='dt_criacao',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='usuariologin',
            name='dt_edicao',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='usuariologin',
            name='user_criacao',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='usuariologin',
            name='user_edicao',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterModelTable(
            name='usuario',
            table='usuario',
        ),
    ]
