# Generated by Django 4.2.7 on 2023-12-15 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True, null=True)),
                ('dt_criacao', models.DateTimeField(null=True)),
                ('dt_edicao', models.DateTimeField(null=True)),
                ('user_criacao', models.CharField(max_length=255, null=True)),
                ('user_edicao', models.CharField(max_length=255, null=True)),
                ('cep', models.CharField(max_length=10, null=True)),
                ('cep_form', models.CharField(max_length=15, null=True)),
                ('municipio', models.CharField(max_length=15, null=True)),
                ('bairro_cep', models.CharField(max_length=100, null=True)),
                ('endereco_cep', models.CharField(max_length=100, null=True)),
                ('endereco_comp_cep', models.CharField(max_length=200, null=True)),
                ('latitude_cep', models.CharField(max_length=200, null=True)),
                ('longitude_cep', models.CharField(max_length=200, null=True)),
                ('tipo_cep', models.CharField(max_length=200, null=True)),
                ('celular_numero', models.CharField(max_length=50, null=True)),
                ('celular_ddd', models.CharField(max_length=3, null=True)),
                ('celular_completo', models.CharField(max_length=50, null=True)),
                ('celular_completo_form', models.CharField(max_length=50, null=True)),
                ('telefone_numero', models.CharField(max_length=50, null=True)),
                ('telefone_ddd', models.CharField(max_length=3, null=True)),
                ('telefone_completo', models.CharField(max_length=50, null=True)),
                ('telefone_completo_form', models.CharField(max_length=50, null=True)),
                ('email', models.EmailField(max_length=200, null=True)),
                ('email_financeiro', models.EmailField(max_length=200, null=True)),
                ('email_documentacao', models.EmailField(max_length=200, null=True)),
                ('nm_completo', models.CharField(max_length=200, null=True)),
                ('nm_primeiro', models.CharField(max_length=200, null=True)),
                ('nm_ultimo', models.CharField(max_length=200, null=True)),
                ('cpf', models.BigIntegerField(null=True)),
                ('cpf_form', models.CharField(max_length=20, null=True)),
                ('rg', models.CharField(max_length=15, null=True)),
                ('rg_form', models.CharField(max_length=15, null=True)),
                ('dat_nasc', models.DateField(null=True)),
                ('imagem', models.FileField(default='fotos/sem-foto.png', null=True, upload_to='fotos/usuarios')),
                ('sexo', models.CharField(choices=[('masculino', 'Masculino'), ('femenino', 'Femenino'), ('outros', 'Outros')], max_length=9, null=True)),
                ('tela_principal', models.CharField(max_length=255, null=True)),
            ],
            options={
                'db_table': 'cliente',
            },
        ),
    ]
