# Generated by Django 4.2.7 on 2023-11-20 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True, null=True)),
                ('logo', models.CharField(default='empresa/logo/sem-logo.png', max_length=2048, null=True)),
                ('cor_principal', models.CharField(max_length=10, null=True)),
                ('cor_secundaria', models.CharField(max_length=10, null=True)),
                ('nome', models.CharField(max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ModuloEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True, null=True)),
                ('nome', models.CharField(max_length=255, null=True)),
                ('acesso', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
