# Generated by Django 4.2.7 on 2023-12-15 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client_core', '0003_tipo_delete_empresa_delete_moduloempresa'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tipo',
        ),
    ]
